apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-expressjs-non-prod
  namespace: argocd
spec:
  destination:
    namespace: non-prod  # Namespace for non-prod environment
    server: https://34.165.59.91
  project: helloworld-expressjs-non-prod  # Reference the non-prod project
  source:
    helm:
      valueFiles:
        - values.yaml  # Non-prod specific values file
    repoURL: git@github.com:elitamsut/node-app.git  # Your repository
    path: helloworld-expressjs  # Path to the Helm chart
    targetRevision: develop  # Use the develop branch for non-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

